apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: logging-api-token
spec:
  encryptedData:
    token: AgCZhpVu2/cMKJm4HCfIzmq6dQTvt0Midcd6hxKhxj0t1HZRVQ1FE3v7gODTp9qDQILmQ9jFwXRXdEA0K0ePH+ZePkdNAapX2mfqTlL2tnFqojdAM5hw9gWmO4oHGAdAunBtP25mdfViEKoHTiWIXgTFNgWHOeA4dak+/8AcjsEbPlVwEf4newC5mo1uiUoOOhvNxT/8OIHKnz/gwmsiUmB2khZf4T6ic7k1Ky5T/qgLMl3B5yg8fbzUmO6bTp1ukbmojrMAcJg2CJZsrXE37eFFWMnOMKxEZrA61LILBN5k2pCU9GI7JLraT4JIOuGSqWov9DwHXNr+Pacgg7lMiuFPhZcZLXfMV6FLW8tLCKRlmCXB+zo9ohwW8OPdH40sqRcDQirY4qgjf+KVKAA/yfcL+6K3CmTyhORbQzwDVn56jzSX+KGe7Id32jDbFfU5t6LderPRdYr0p92ACvI2xfkS496rUq2CbcztTFS1U+mVh4j1i3DMXGZt2pSCnYUHjO4vuqoaWIQXOFxYzj2gZ6gU/HcMeIdrg+6d7r2Fgg5Rlk1HEENTTfymwKy2m9xoAxGug95aI6x8oY/u53nlE5aO5qndh4bWmOHYO1mdbxdLYkPxZHHnfUBIsyblRgN6y8V+qspMxsAzq5/I29icSTruf6jWu/kPxVvZRAQ/HkBeCHXMJTYH5FGiJ9/aAhdJWUcrZpsJDbZ7/eo6cdweYhZcZdyK
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: logging-api-token

