apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: database-password
spec:
  encryptedData:
    password: AgAs1ygFklf2DI1E3yhwqwyfDShpySos5aWwnKNmPDTI3SKjI0tas9ah+8qa8RErs43CAMvLdswtAVNilwGCjYj38lDqOwLJx+MMa1GUm00yhI1dx0e6MVsRTJ7xZIkeqUqZPXR3wKhBzZNF5ru/Fm3L2oPNciYMLwPasoApkjxGKxYoZBDGKGlcnvtjW7dO30RO7PdzbS6aD7c917H8YXge3O/1PTZIE4qIblUg1NlkETyfYUOoQVgvexpMbuKYQgLxZ7wZOnTirk3i27s99c/v08J2YgU0V3BkzqLXfrZg+uV5N9GAuhSfJ0d2smzghOu22Kt6e/8Xku0nx/FhAaRjkcCMDIHpCxaBGi80Sm5ww/uJhL+uI2BXYCEKmpB7CJQDprIGN2b8s4KOLsysMePmXb5e42wFxpjT/rYV55fzN4+So46ncdqIa7cIT173uADncm47ZuFdAuAxQKzbspRJmHOHehCEOjJdFhAyhdctsUfPlNkXE80rPkO7SntDh9PaEwkRWxwQcAm+U60e57wGzI4rLd2NGbkuKRuVH/FQ3IpkRmHhUBD4eSv+DuzPYUAWGW31vg9NjEUWOY3mb0W267m8QcDhWnWlqXzdEb7bA/AQdeaKMS3rrEDfU/ZsXGpTN5mHOwSunQZi22UD+4KHkTFKJo8nyCQfQDMheKvQwDrybU+QFmdEk7podrcTMiAZtIDeHFrbIz9GGSoDKLtKFLTDyuBUr3xC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: database-password

